### ISSUE TITLE
Please add license file

### ISSUE THREAD

**Issue by slessard** [iwarapter/pingfederate-sdk-go#1]
This project does not specify any kind of license, e.g. MIT, BSD, Apache 2, etc, which means my employer will not allow me to use any portion of this project in any way. Would you consider adding a license file to this project?

May I suggest the MIT license because it is very simple.  https://opensource.org/licenses/MIT

**Comment by iwarapter** [comment]
Hi @slessard, all my others use MIT i just hadn't added for this. Please note, as per the readme this is pretty experimental and mainly used to support the terraform provider as such there is currently guarantee for any API compatibility etc in the client. (also it generated and there are defects in the ping documentation so let me know if you find any issues)
