### ISSUE TITLE
Missing field in OAuth Client model

### ISSUE THREAD

**Issue by rajrohanyadav** [iwarapter/pingfederate-sdk-go#14]
The OAuth client model is missing the `restrictToDefaultAccessTokenManager` field.

![pingfederate-client-model](https://github.com/iwarapter/pingfederate-sdk-go/assets/16662291/2d5bc648-271c-44b2-aa34-c723bcffda0a)

**Comment by iwarapter** [comment]
This is already supported in the [pf11.1](https://github.com/iwarapter/pingfederate-sdk-go/tree/feature/pf11.1) branch
